export default{
    getTimetable:()=>{
        return{
            data:{
                week: 0,
                courses:
                [
                    {
                        index:1,
                        subject:"大学英语",
                        classroom:'2205',
                        teacher:"陈宣",
                    },
                    {
                        index:2,
                        subject:"大学英语",
                        classroom:'2205',
                        teacher:"陈宣",
                    },
                    {
                        index:4,
                        subject:"大学英语",
                        classroom:'2205',
                        teacher:"陈宣",
                    },
                    {
                        index:5,
                        subject:"大学英语",
                        classroom:'2205',
                        teacher:"陈宣",
                    },
                    {
                        index:7,
                        subject:"大学英语",
                        classroom:'2205',
                        teacher:"陈宣",
                    },
                    {
                        index:8,
                        subject:"大学英语",
                        classroom:'2205',
                        teacher:"陈宣",
                    },
                    {
                        index:10,
                        subject:"大学英语",
                        classroom:'2205',
                        teacher:"陈宣",
                    },
                    {
                        index:12,
                        subject:"大学英语",
                        classroom:'2205',
                        teacher:"陈宣",
                    },
                ]
            }
        }
    }
}